board/urls.py
from django.urls import path

from . import views

app_name = "board"
urlpatterns = [
    path("", views.index, name="index"),
    path(
        "update_task_ajax/",
        views.update_task_ajax,
        name="update_task_ajax",
    ),
    path("boards/", views.BoardListView.as_view(), name="boards"),
    path("board/<int:pk>/", views.BoardDetailView.as_view(), name="board"),
    path("board/create/", views.BoardCreateView.as_view(), name="create_board"),
    path(
        "board/<int:pk>/update/", views.BoardUpdateView.as_view(), name="update_board"
    ),
    # path("board/<int:pk>/delete/", views.BoardDeleteView.as_view(), name="delete_board"),
    path(
        "board/<int:board_id>/column/create/",
        views.ColumnCreateView.as_view(),
        name="create_column",
    ),
    # path(
    #     "board/<int:board_id>/column/<int:pk>/update/",
    #     views.ColumnUpdate.as_view(),
    #     name="update_column",
    # ),
    # path(
    #     "board/<int:board_id>/column/<int:pk>/delete/",
    #     views.ColumnDelete.as_view(),
    #     name="delete_column",
    # ),
    path(
        "board/<int:board_id>/task/<int:pk>/",
        views.TaskDetailView.as_view(),
        name="task",
    ),
    path(
        "board/<int:board_id>/column/<int:column_id>/task/create/",
        views.TaskCreateView.as_view(),
        name="create_task",
    ),
    path(
        "board/<int:board_id>/task/<int:task_id>/update/",
        views.TaskUpdateView.as_view(),
        name="update_task",
    ),
    path(
        "board/<int:board_id>/task/<int:task_id>/delete/",
        views.TaskDeleteView.as_view(),
        name="delete_task",
    ),
]

personal_kanban/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path("", include("board.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
]

board/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Board(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Boards"
        ordering = ["id"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("board:board", args=[str(self.pk)])


class Column(models.Model):
    title = models.CharField(max_length=255)
    board = models.ForeignKey("Board", related_name="columns", on_delete=models.CASCADE)
    date_creted = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Task(models.Model):
    class Priority(models.TextChoices):
        HIGH = "H", "High"
        MEDIUM = "M", "Medium"
        LOW = "L", "Low"

    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    priority = models.CharField(
        max_length=1,
        choices=Priority.choices,
        default=Priority.MEDIUM,
    )
    board = models.ForeignKey("Board", related_name="tasks", on_delete=models.CASCADE)
    column = models.ForeignKey("Column", related_name="tasks", on_delete=models.CASCADE)
    task_order = models.PositiveIntegerField(default=0, editable=False, db_index=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.id} - {self.title}"

    class Meta:
        ordering = ["task_order"]
        verbose_name_plural = "Tasks"

board/forms.py
# create forms to models in board/models.py

from django import forms
from .models import Board, Column, Task


class BoardForm(forms.ModelForm):
    # write code here
    class Meta:
        model = Board
        fields = "__all__"


class ColumnForm(forms.ModelForm):
    # write code here
    class Meta:
        model = Column
        fields = ["title"]


class TaskForm(forms.Form):
    class Meta:
        model = Task
        fields = [
            "title",
            "description",
            "column",
            "priority",
        ]

board/views.py
import json
import os

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template import loader
from django.urls import reverse
from django.views import View, generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import BoardForm, ColumnForm, TaskForm
from .models import Board, Column, Task


def index(request):
    boards = Board.objects.all()
    template = loader.get_template(template_name="board/index.html")

    number_of_visits = request.session.get("number_of_visits", 0)
    request.session["number_of_visits"] = number_of_visits + 1
    print(f"Number of visits: {number_of_visits}")
    context = {"boards": boards, "number_of_visits": number_of_visits}
    return render(request, "board/index.html", context)


# BOARD views
class BoardListView(LoginRequiredMixin, generic.ListView):
    model = Board
    template_name = "board/boards.html"
    context_object_name = "boards"

    def get_queryset(self):
        return Board.objects.filter(owner=self.request.user)


class BoardDetailView(LoginRequiredMixin, generic.DetailView):
    model = Board
    template_name = "board/board.html"
    context_object_name = "board"

    # Overriding the get_queryset method to filter the boards by the owner and restrict access to the boards for users who are not the owner.
    def get_queryset(self):
        return self.model.objects.filter(owner=self.request.user)


class BoardCreateView(LoginRequiredMixin, CreateView):
    model = Board
    template_name = "board/board_create.html"
    fields = ["name", "description"]

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("board:board", args=[self.object.id])


class BoardUpdateView(LoginRequiredMixin, UpdateView):
    model = Board
    template_name = "board/board_update.html"
    fields = ["name", "description"]

    def get_queryset(self):
        return self.model.objects.filter(owner=self.request.user)

    def get_success_url(self):
        return reverse("board:board", args=[self.object.id])


# COLUMN views


class ColumnCreateView(LoginRequiredMixin, CreateView):
    model = Column
    template_name = "board/column_create.html"
    fields = ["title"]

    def get_success_url(self):
        return reverse("board:board", args=[self.kwargs.get("board_id")])

    def form_valid(self, form):
        form.instance.board = Board.objects.get(id=self.kwargs["board_id"])
        return super().form_valid(form)


# TASK views


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    template_name = "board/task.html"
    context_object_name = "task"

    def get_queryset(self):
        return self.model.objects.filter(board__owner=self.request.user)


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "board/task_create.html"
    fields = ["title", "description", "priority"]

    def get_success_url(self):
        return reverse("board:board", args=[self.kwargs.get("board_id")])

    def form_valid(self, form):
        form.instance.column = Column.objects.get(id=self.kwargs["column_id"])
        form.instance.board = self.get_board()
        return super().form_valid(form)

    def get_board(self):
        board_id = self.kwargs.get("board_id")
        return Board.objects.get(id=board_id)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = "board/task_update.html"
    fields = ["title", "description", "priority"]
    pk_url_kwarg = "task_id"

    def get_success_url(self):
        return reverse("board:board", args=[self.kwargs.get("board_id")])

    def get_queryset(self):
        return self.model.objects.filter(board=self.get_board())

    def get_board(self):
        board_id = self.kwargs.get("board_id")
        return Board.objects.get(id=board_id)


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = "board/task_delete.html"
    pk_url_kwarg = "task_id"

    def get_success_url(self):
        return reverse("board:board", args=[self.kwargs.get("board_id")])

    def get_queryset(self):
        return self.model.objects.filter(board=self.get_board())

    def get_board(self):
        board_id = self.kwargs.get("board_id")
        return Board.objects.get(id=board_id)


def update_task_ajax(request):
    if request.method == "POST":
        body = json.loads(request.body)
        task_id = body.get("task_id")
        column_id = body.get("column_id")
        try:
            task = Task.objects.get(pk=task_id)
            column = Column.objects.get(pk=column_id)
        except Task.DoesNotExist:
            return JsonResponse({"status": "error"})
        task.column = column
        task.save()
        return JsonResponse({"status": "success"})

board/templates/board/board.html
{% extends "base.html" %} 
{% load static %}

{% block title %}
    {{board.name}}
{% endblock %}

{% block content%}

<div class="container">
    {% for column in board.columns.all %}

            <div class="column" id="{{column.pk}}" >
                <div class="flex-container column-header">
                    <h3>{{column.title}}</h3>
                    <a href="{% url "board:create_task" board.pk column.pk %}" >
                        <div class="plus">
                            <div class="bar1"></div>
                            <div class="bar2"></div>
                        </div>
                    </a>
                </div>
                {% for task in column.tasks.all %}
                    <div class="task card" id = "{{task.id}}"draggable=true><a href="{% url "board:update_task" board.pk task.pk %}">{{task.title}}</a></div>
                {% endfor %}
            </div>
    {% endfor %}
    <div class=""><div class="container">
        <button><a href="{% url "board:create_column" board.pk %}"><i class="fa-solid fa-circle-plus"></i></a></button>
    </div></div>
</div>

<script src="{% static 'board/js/board.js' %}"></script>

{% endblock %}

board/templates/board/board_create.html
{% extends "base.html" %} 
{% load static %} 
{% block content%}

<h1>Create a new board</h1>

{% endblock content %}

board/templates/board/board_update.html
{% extends "base.html" %} 
{% load static %} 
{% block content%}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

board/templates/board/boards.html
{% extends "base.html" %} 
{% load static %} 
{% block content%}

{% if boards %}
<div class="container">
    <ul>
        {% for board in boards %}
            <div class="card"><a href="{{ board.get_absolute_url }}">{{ board.name }}</a></div>
        {% endfor %}
        {% else %}
            <div class="card">No boards found</div>
        {% endif %}
    </ul>
</div>

<button><a href="{% url 'board:create_board' %}">Create a new board</a></button>

{% endblock %}

board/templates/board/column_create.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="center-page">
        <form method="post">
        {% csrf_token %}
            {{form.as_p}}
        <input type="submit" value="update">
        </form>
    </div>
</div>
{% endblock content %}

board/templates/board/index.html
{% extends "base.html" %} 
{% load static %} 
{% block content%}

{% if boards %}
<div class="container">
    <ul>
        {% for board in boards %}
            <div class="card"><a href="/board/{{ board.id }}">{{ board.name }}</a></div>
        {% endfor %}
        {% else %}
            <div class="card">No boards found</div>
        {% endif %}
    </ul>
</div>

<p>Is staf? {{user.is_staff}}</p>
<p>You have visited this page {{ number_of_visits }} time{{ number_of_visits|pluralize }}.</p>
{% endblock %}

board/templates/board/task.html
<h1>This is a task details' page</h1>

board/templates/board/task_create.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="center-page">
        <form method="post">
        {% csrf_token %}
            {{form.as_p}}
        <input type="submit" value="Create">
        </form>
    </div>
</div>
{% endblock content %}

board/templates/board/task_delete.html
{% extends "base.html" %}
{% load static %}


{% block content %}
  <h1>Delete Task</h1>

<p>Are you sure you want to delete the task: {{ task }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>
{% endblock %}

board/templates/board/task_update.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="center-page">
        <form method="post">
        {% csrf_token %}
            {{form.as_p}}
                <div class="form-button">
                    <button><a href="{% url "board:delete_task" task.board.pk task.pk %}">Delete task</a></button>
                    <input type="submit" value="update">
                </div>
        </form>
    </div>
</div>
{% endblock content %}